### ISSUE TITLE
[CoreShop2] Ecommerce Bridge

### ISSUE THREAD

**Issue by dpfaffenbauer** [coreshop/CoreShop#176]
Implement a Bridge between CoreShop and the ecommerce framework. So the ecommerce framework could use CoreShop features.

Since the framework loads classes using a config, CoreShop could provide Bridge Classes where it implements Ecommerce Interfaces and you could configure the framework to use CoreShop Bridge. Therefore, the framework could use CoreShop features as well.

**Comment by dpfaffenbauer** [comment]
@fashxp Here is what I already tried, not much, but you should see the idea: https://github.com/coreshop/CoreShop/commit/a422c2235b951d56341170f3bbf5a28bb141e6dc

Nothing tested yet, this is just like a proof-of-concept, but looks good to me, should work fine.

**Comment by fashxp** [comment]
Looks good so far for me too. 
Could you help me out a bit with the questions: What exactly do you want to archive with the bridge? What would be the use cases that should be covered?

**Comment by fashxp** [comment]
in terms of the config just for your info ... we have the intention to replace the ecommerce framework factory with the Symfony container. but this should be more advantage than disadvantage for this bridge.

**Comment by dpfaffenbauer** [comment]
Right now its more like a proof-of-concept. But it could connect the Framework to CoreShop, so somebody could use the best of both platforms. 

For example: If somebody wants to use the framework, but still likes the way CoreShop does carriage calculation, the bridge gives you an idea how to do this. Another example: CoreShop provides a lot of nice UI's in backend, if somebody likes the UI's and still wants to use the Framework, for whatever reason, the bridge should be the connector to do that.

As already said, its more like a concept for now and hasn't been thought thru yet. Thats why I never pushed it to github before.

**Comment by Yivan** [comment]
Thanks @dpfaffenbauer @fashxp for discussion about making some bridge beetween those two nice ecommerce framework!

Having possibility to use CoreShop UI with the Pimcore ecommerce framework would be great.

For reference, for those interrested on the subject CoreShop/Pimcore ecommerce framework, a discussion has been started here https://groups.google.com/forum/#!topic/pimcore/UxGzeceoZJw.

@fashfxp like dpfaffenbauer said on this forum thread, Pimcore ecommerce service was not usable as it for CoreShop2. Is there any way you can make change (or maybe some are already planned) on the framework to make it like totally independant bundles so CoreShop could rely on it for some core functionnality ? This way developper have to learn only one framework API (the Pimcore framework) but can have the extended functionnality of CoreShop and the complete backend UI for managing the shop. Developper using already the Pimcore framework could rapidly extend it with CoreShop too.

This is just idea. I know CoreShop / Pimcore ecommerce framework are different project, different people, with maybe not the same goals, but maybe some more co-developpement on both project to make them more tied could bring better ecommerce solution to Pimcore... If it should happen it is now as both project are not released. After it will be more harder (because more backward compatibility needed).

**Comment by dpfaffenbauer** [comment]
@Yivan the framework would need to be refactored totally in order for CoreShop to depend on it. CoreShop has a total different approach in solving the ecommerce problem then the framework has. Refactoring the framework in a way, I could depend on it, would break BC for them, and thats not an option for the framework team.

For example: CoreShop uses Doctrine ORM for its own entities, I guess the framework would never do that unless Pimcore uses Doctrine ORM as well (and I think thats not gonna happen for 5, maybe for 6, don't know what the plans are). The frameworks approach on this is to use Pimcore Objects, which, makes totally sense. 

The reason CoreShop doesn't do that is: You are very limited in UI for Pimcore Objects. And I don't really need a Object for a Currency or Country.

CoreShops 2 approach is to be as decoupled as possible, you can now even use the IndexBundle without using CoreShop at all, and create indexes for all kinds of Objects. Even all the UI stuff is decoupled and can be used without CoreShop's core. So, you could say that every CoreShop Bundle is a separate Pimcore Plugin. Everything in CoreShop can be changed/overwritten without touching the core itself. 

And of course: CoreShop is a ecommerce Suite as well, it gives you tools you need for most ecommerce systems.

The framework itself is decoupled as well, but still uses a different approach to do that. It uses its config file to inject dependencies. So it already used some kind of dependency injection. 

And even when they change it to use Symfony Container, I wouldn't even use it as CoreShops base. CoreShop 2 is very close to BETA, not much is missing, it would take me a lot of time refactoring all the stuff again, and creating a lot of PR's to change the Framework in a way it would support everything CoreShop can do. And, I am not even sure this PR's would get accepted.

The idea behind a Bridge is only experimental, as already said: I am not really sure what the real purpose of that could be. 

 * Maybe using CoreShops UI for the Framework? Well, but, why not use CoreShop at all? Everything the framework can do, CoreShop can do as well and even more. 
* The Bridge could allow existing installations to adapt on what CoreShop already provides. Like shipping calculation or specific product prices or whatever. Thats the only advantage of a Bridge I can see.

That being said: It still is an experimental idea and needs to be tested for usability and meaningfulness

**Comment by solverat** [comment]
Just my two cents: I don't think this is a good idea in general. coreshop is a complex ecommerce system with a lot of build-in great features and a superawesome gui. against the framework, coreshop ships everything, a shop system must provide. To build a bridge will just overcomplicate things since the _ecommerce framework_ tries to do the same as coreshop does just with more "pimcore-flavor", without a gui and frontend. So it's literally a bridge from earth to the moon. 

And after all, what are the real benefits of this? Keep an eye on two systems and study two doc trees? Learn and follow two strategies? Combine heaven and earth? coreshop2 is going to be a superb symfony application (just think about the implemented payum strategy or the checkout manager => **f**** great stuff**) and there are still a lot of ideas for the future. Since the _ecommerce framework_ basically provides a extended pimcore object with some nice-to-have ecommerce helpers, it will take hours of conception before writing one single line of code...

The best thing to do would be: Leave the _ecommerce framework_ behind and support coreshop. :) Everything else is more of a step back than a step forward.

**Comment by dpfaffenbauer** [comment]
IMO: Still would be a good idea, but there is not time to do that. It's totally possible for CoreShop's components being used inside the framework context. If somebody needs that, they can do it project specific.
