### ISSUE TITLE
[CoreShop2] Login and logout runs into RuntimeException

### ISSUE THREAD

**Issue by daniel-travix** [coreshop/CoreShop#184]
in vendor/coreshop/core-shop/src/CoreShop/Bundle/FrontendBundle/Controller/SecurityController.php (line 81) 

> You must configure the check path to be handled by the firewall.

**Comment by dpfaffenbauer** [comment]
well, just tried it. Since you have installed the Pimcore DEMO, which comes with a firewall that listens to all requests, you now have 2 firewalls which are configured to listen to the same request. Latest Firewall registered wins, so I consider this issue more of a Configuration Issue then a CoreShop Issue,
