### ISSUE TITLE
Checkout / Cart

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#264]
### Cart / Summary
- Remove render controller, from cart- and checkout summary, use an include. Something like `{% include '@CoreShopFrontend/Shared/cart_summary.html.twig' with {editAllowed: true|false} %}`
- Do not allow cart modification in summary

### Cart / Checkout Route
- ~There is `/shop/cart` route and a `Cart/summary` view: correct~
- ~There is also a `shop/checkout/cart` route (and `Checkout/steps/cart` which actually never gets loaded): from cart the "continue" leads me to `shop/checkout/cart` which directly transfers me to the first checkout step. So why the `shop/checkout/cart` route?~
 > This will be fixed with #260.

**Comment by dpfaffenbauer** [comment]
# Cart / Summary
1. Not possible, since the cart quantity update needs a form
2. why? Shouldn't the customer have the possibility to change on last step?

# Cart / Checkout Route
 - steps/cart is a checkout step which currently has no real purpose, thats right, but where to start with checkout? Cart is the first step and kinda redirects to the next step

**Comment by solverat** [comment]
1. ah ok
2. nope - on summary there is no way to change a thing.

**Comment by dpfaffenbauer** [comment]
2. fixed, introduced a seperate html table for summary

What about the routes?!

**Comment by solverat** [comment]
done.
