### ISSUE TITLE
Fix evil Container Getter

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#285]
@dpfaffenbauer should we keep [this](https://github.com/coreshop/CoreShop/blob/1da4408dfcccd9ec0e9b902b212218b113bd858d/src/CoreShop/Component/Order/Model/Order.php#L252) and wait until pimcore allows nice DI in pimcore objects?
**If** we keep it: remove all `getOrder*Repository` and use the order object directly. Otherwise we need to find a hacky way to get the relations in state machine callbacks, like [here](https://github.com/coreshop/CoreShop/blob/ae177e992e85a1b2b12a13afacb08e1a29bc0480/src/CoreShop/Bundle/OrderBundle/Resources/config/app/workflow/coreshop_order.yml#L42).

**Comment by dpfaffenbauer** [comment]
1. ClassDefinitions are not possible, since the way Pimcore handles it.
2. getOrder*Repository is possible, I'll look into it.

**Comment by dpfaffenbauer** [comment]
1. Pimcore would need to refactor the way they create and store ClassDefinitions. Currently, they store a definition_*.php file with static file-names. To solve that, they would need to either store it as xml/yml or json definition file. Then, instead of using FQCN, they would need to use identifiers, eg. instead of ```CoreShop\Bundle\CurrencyBundle\CoreExtension\Currency``` simply ```coreShopCurrency```, that is then fetched from a registry/service-locator.

**Comment by dpfaffenbauer** [comment]
fixed as good as possible. unfortunately not possible with pimcore object tags
