### ISSUE TITLE
Move Events out of Controller

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#316]
- `coreshop.cart.update` in CartController
- `coreshop.cart.item_added` in CartController
- `coreshop.cart.item_removed` in CartController
- `coreshop.customer.request_password_reset` in RegisterController
- `coreshop.customer.password_reset` in RegisterController

**Comment by dpfaffenbauer** [comment]
done for item_add and item_remove, but currently not possible for cart.update -> this is because the form itself changes the quantity and therefore the modifier is not called. This is only available inside this controller.

customer.request_password_reset and customer.password_reset is also only available inside the controller

**Comment by dpfaffenbauer** [comment]
also changed item_add and item_removed to item_add_pre, item_add_post as well as item_remove_pre and item_remove_post to be more consistent

**Comment by solverat** [comment]
## New Events

- `coreshop.customer.settings.update_post`
- `coreshop.customer.address.update_post`
- `coreshop.customer.address.delete_pre`
- `coreshop.customer.address.delete_post` (skip it?)
