### ISSUE TITLE
Backend Order Creation does not save language

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#398]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Steps to reproduce:
Create a new order and set a different language, german for example:
![order-german](https://user-images.githubusercontent.com/2771909/38425582-8fa8d4d4-39b4-11e8-9781-7fc329758364.png)
It'll not be saved and the default language will be assigned to the order:
![order-english](https://user-images.githubusercontent.com/2771909/38425597-9db1f466-39b4-11e8-83be-a89fb0184a72.png)

This leads to invoices in the wrong language and further issues.

I believe that language is not properly assigned here: https://github.com/coreshop/CoreShop/blob/3b63bec32bad078aaab24d61f04f45ba0baa7d71/src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleCreationController.php#L303
It's being saved before as far as I could debug this: https://github.com/coreshop/CoreShop/blob/3b63bec32bad078aaab24d61f04f45ba0baa7d71/src/CoreShop/Bundle/OrderBundle/Controller/AbstractSaleCreationController.php#L234

**Comment by dpfaffenbauer** [comment]
this commit should fix it: https://github.com/coreshop/CoreShop/commit/d825a2d03f77632da38be14d905487fe24bafdf5

What it changes:
 - Use Pimcore Locale Fallback if not fallback is found by using `findLocale`instead of `getLocale` on Pimcores locale Service
 - Don't use the LocaleContext inside the SaleTransformer, store the locale inside the cart and use it for order-creation.

**Comment by dpfaffenbauer** [comment]
this is fixed now
