### ISSUE TITLE
Another sites which are not configured as a CoreShop throw a exception

### ISSUE THREAD

**Issue by albertmueller** [coreshop/CoreShop#418]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If i setup a new page as site and these has no CoreShop store configuration, try to access gives me back a exception:
![image](https://user-images.githubusercontent.com/2986829/38916071-42e7eeba-42e6-11e8-98d7-def985bdb660.png)

**Comment by dpfaffenbauer** [comment]
hmmm... well, coreshop asumes that every page belongs somehow to a shop. we'd need a system that determines if a site is actually a shop or not and implement that on all listeners....

@solverat what do you say?

**Comment by solverat** [comment]
yea i have/had the same problem. Since pimcore allows true multisites (one could be a big store, the next a simple webpage with a collection of cute cat videos) we need to find a way to determinate a valid coreshop context. Currently you need to define a dummy store for all your sites...

Since this must happen in a very early state we may need to implement a `hasCoreShopInstance()` resolver which loads valid/invalid sites from a configuration/backend setting. With that, the store configuration itself also fetches available sites from that resolver.

**Comment by dpfaffenbauer** [comment]
I was more thinking about the following: 

If site has store -> it is CoreShop
If not, it's no CoreShop

If the dev tries to use something from the CoreShop API on an invalid site, he gets an exception.

**Comment by Cruiser13** [comment]
I'd not go for that solution @dpfaffenbauer . We might want to use some stuff from coreshop without a store on that site. Think about B2B store hidden and some information landing page on a separated domain - but we might want to give the user a personal greeting there or something like this if he has a b2b store session.
Defining a dummy store means filling all values, handling all products for that dummy store too.

**Comment by dpfaffenbauer** [comment]
as soon as you want to show prices on a non-coreshop page, you would get errors anyway. When you use CoreShop with my proposed solution and there is no Store, the price-calculation for a product will fail. It would have no context, no currency, no price, no country, nothing.

**Comment by dpfaffenbauer** [comment]
should be fine now
