### ISSUE TITLE
Title / Meta Data Generation

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/CoreShop#429]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

I believe we should have some default methods/standard implementations for setting title and meta data for products, categories and other stuff. At the moment you have to rewrite every template to add some var which you can output in the layout for title and metadata. The demo does simply output "Coreshop" everywhere as title but that's no real solution.
If we tackle this we might also think about og metadata and maybe include structured markup ( e.g. https://developers.google.com/search/docs/data-types/product )

What do you think?

**Comment by solverat** [comment]
Also related with #413. Currently we do not have any special strategy for this. In Pimcore News for example i've created a event listener which calls a meta generator for `title`, `description` and `meta`, see here:

https://github.com/dachcom-digital/pimcore-news/blob/master/src/NewsBundle/EventListener/MetaDataListener.php

https://github.com/dachcom-digital/pimcore-news/blob/master/src/NewsBundle/Generator/HeadMetaGenerator.php

**Comment by dpfaffenbauer** [comment]
Maybe we can find a generic solution for that? So that your bundles behave the same as CoreShop. Maybe something like a pimcore-seo-bundle? There would be a interface to implement and that interface handles SEO informations. What do you think @solverat? I could create a coreshop/seo-bundle for that and a coreshop/seo component and news-bundle can use that as dependency.

**Comment by dpfaffenbauer** [comment]
implemented with SEO Bundle
