### ISSUE TITLE
Wrong Discount Tax Calculation

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#579]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Store / Condition: All prices are without taxes
- Add product (Price `CHF 15.90` with Tax of `7.7%`)
- Apply discount rule (Amount `CHF 10,-`)

## Expected Results
Discount with taxes: `CHF 10.77`

## Current Result
Discount with taxes: `CHF 10.71`

**Comment by dpfaffenbauer** [comment]
To be honest, there is no easy solution for this. The problem is that each item in the cart could have different taxes applied to it. To calculate the average tax percentage will never give you an accurate discount tax.

A solution would be to distribute the discount on the items before any tax is calculated.
