### ISSUE TITLE
Rounding issue in Cart Overview

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#580]
| Q                | A
| ---------------- | -----
| Bug report?      | unknown / yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Condition: All prices are without taxes

- add product with price `15.90` and taxes of `7.7%`.
- add product to cart
- change amount to `2` eg. `4`

### List with 2 pieces
![bildschirmfoto 2018-08-13 um 21 23 27](https://user-images.githubusercontent.com/700119/44053274-751bd3f0-9f3f-11e8-9723-6ee8390ad234.png)

### List with 4 pieces
![bildschirmfoto 2018-08-13 um 21 30 16](https://user-images.githubusercontent.com/700119/44053517-2f47c41e-9f40-11e8-8abb-d0aa2535345d.png)

## Expected Result
- Missmatch between subtotal and total taxes

**Comment by dpfaffenbauer** [comment]
What do you expect the numbers to be?!

**Comment by solverat** [comment]
## 2 Pieces:
Subtotal excl. (`31.80`) + Tax total (`2.45`) = `34.25`, displays `34.24`.

## 4 Pieces:
Subtotal excl. (`63.60`) + Tax total (`4.90`) = `68.50`, displays `68.48`.

**Comment by dpfaffenbauer** [comment]
Ok, its quite obvious why that happens. The reason is how CoreShop currently calculates taxes.

Example for you to easier understand the problem:

Item Price: `15.90`
Item Price with tax: `17.12`
Tax: `1.22`

Two Items: `31,8`
Two items with tax: 34.248` => and that is where the issue happens.

CoreShop doesn't currently calculate the total item price based on its whole tax value, it does it on multiplying the Item Price * Quantity. => 34,24 where the actual price should be 34.25

I'll prepare a WIP PR for this.

**Comment by dpfaffenbauer** [comment]
@grammit can you apply PR #584 and test again with this PR?
