### ISSUE TITLE
Introduce 'street2' field to the CoreShopAdress DataObject

### ISSUE THREAD

**Issue by davidhoeck** [coreshop/CoreShop#989]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes/no

Street2 can be used to store the door, floor or any other additional information. The name 'street2' is also used by some payment providers or carriers.

**Comment by solverat** [comment]
Hello @davidhoeck,

I don't think this is necessary in core. As there could be plenty of other "possible" address fields (street 2, street 3, district, second pre-name and so on) this will lead to a never ending story. 

The`CoreShopAddress` object should be simple as possible (also checkout this discussion #665) because in fact, it's even harder to remove unwanted fields, if you don't need them.

So, if you need an additional field, just change the parent class of the object and point it a new `AppBundle\Model\Address` class. Second, create a `AddressTypeExtension` in `AppBundle\Form\Extension` and you're good to go.

**Comment by davidhoeck** [comment]
@solverat personally I think `street2` should become a default field because, especially for addresses in bigger cities you need to define which floor, door or whatever you have. Most of the online shops I know have a field like that - the naming could be changed to `streetAddition` or something like that.

**Comment by Wowa1122** [comment]
Entschuldigung für verspetung:).

David Höck <notifications@github.com> schrieb am Fr., 17. Mai 2019, 17:37:

**Comment by dpfaffenbauer** [comment]
true and false. Some systems only use the number in a format like 9-11/N3 (N3 for door number). If you look into Vienna, you have to input a Floor, Staircase, Door Number, but they can do it with slashes as well. So, its not a big deal. If you have to have it, you know how to add it ;)
